// import { LanguageProvider } from './context/LanguageContext';
// import './globals.css';


// export const metadata = {
//   title: 'Your App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <LanguageProvider>
//           {children}
//         </LanguageProvider>
//       </body>
//     </html>
//   );
// }



import { LanguageProvider } from './context/LanguageContext';
import './globals.css';
import { FaWhatsapp } from 'react-icons/fa';

export const metadata = {
  title: 'Your App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LanguageProvider>
          {children}

          {/* Floating WhatsApp Icon (with float animation) */}
          <a
            href="https://wa.me/919610719306"
            target="_blank"
            rel="noopener noreferrer"
            className="fixed bottom-6 right-6 z-50 bg-green-500 hover:bg-green-600 text-white p-4 rounded-full shadow-[0_0_20px_4px_rgba(72,211,132,0.6)] hover:scale-105 transition-transform duration-300 animate-float"
            aria-label="Chat on WhatsApp"
          >
            <FaWhatsapp className="text-3xl" />
          </a>
        </LanguageProvider>
      </body>
    </html>
  );
}
